version: '3.9'
services:
  api:
    build: api
    depends_on:
      - db
    environment:
      - DB_URL=postgres://${DB_USER}:${DB_PASS}@db/${DB_NAME}
      - TAXJAR_API_KEY=${TAXJAR_API_KEY}
    ports:
      - 3000:3000
  db:
    build: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    ports:
      - 5432:5432
  ui:
    build: ui
    depends_on:
      - api
    ports:
      - ${WEB_PORT}:80
