version: '3.9'
services:
  api:
    build: api
    depends_on:
      - db
    environment:
      - 'DB_URL=postgres://postgres:palitronica@db/palitronica'
    ports:
      - '3000:3000'
  db:
    build: db
    environment:
      - POSTGRES_PASSWORD=palitronica
      - POSTGRES_DB=palitronica
    ports:
      - '5432:5432'
  ui:
    build: ui
    depends_on:
      - api
    ports:
      - '5000:80'
