version: "3.9"
services:
  api:
    build:
      context: api
      args:
        - password
    depends_on:
      - db
    environment:
      - DB_URL=postgres://postgres:${password}@db/palitronica
    ports:
      - "8000:8000"
  ui:
    build: ui
    ports:
      - "5000:80"
  db:
    build:
      context: db
      args:
        - password
    environment:
      - POSTGRES_PASSWORD=${password}
    ports:
      - 5432:5432
